updated docker config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,13 +45,13 @@ jobs:
               if [ -f  docker-compose -f docker-compose.prod.yml] || [ -f  docker-compose -f docker-compose.prod.yml ]; then
                 # Check Docker and Docker Compose installation
                 docker --version || (echo "Docker is not installed" && exit 1)
-                 docker-compose -f docker-compose.prod.yml --version || (echo "Docker Compose is not installed" && exit 1)
+                 docker-compose --version || (echo "Docker Compose is not installed" && exit 1)
                  docker-compose -f docker-compose.prod.yml down
                  docker-compose -f docker-compose.prod.yml pull
                  docker-compose -f docker-compose.prod.yml build
                  docker-compose -f docker-compose.prod.yml up -d
               else
-                echo " docker-compose -f docker-compose.prod.yml.yml file not found, skipping Docker commands"
+                echo " docker-compose -f docker-compose.prod.yml file not found, skipping Docker commands"
                 exit 1
               fi
             else
